<?php

return [
    'ace' => ['countryCode' => 'ace', 'name' => 'Achinese', 'script' => 'Latn', 'native' => 'Aceh'],
    'af' => ['countryCode' => 'af', 'name' => 'Afrikaans', 'script' => 'Latn', 'native' => 'Afrikaans'],
    'agq' => ['countryCode' => 'agq', 'name' => 'Aghem', 'script' => 'Latn', 'native' => 'Aghem'],
    'ak' => ['countryCode' => 'ak', 'name' => 'Akan', 'script' => 'Latn', 'native' => 'Akan'],
    'an' => ['countryCode' => 'an', 'name' => 'Aragonese', 'script' => 'Latn', 'native' => 'aragonés'],
    'cch' => ['countryCode' => 'cch', 'name' => 'Atsam', 'script' => 'Latn', 'native' => 'Atsam'],
    'gn' => ['countryCode' => 'gn', 'name' => 'Guaraní', 'script' => 'Latn', 'native' => 'Avañe’ẽ'],
    'ae' => ['countryCode' => 'ae', 'name' => 'Avestan', 'script' => 'Latn', 'native' => 'avesta'],
    'ay' => ['countryCode' => 'ay', 'name' => 'Aymara', 'script' => 'Latn', 'native' => 'aymar aru'],
    'az' => ['countryCode' => 'az', 'name' => 'Azerbaijani (Latin)', 'script' => 'Latn', 'native' => 'azərbaycanca'],
    'id' => ['countryCode' => 'id', 'name' => 'Indonesian', 'script' => 'Latn', 'native' => 'Bahasa Indonesia'],
    'ms' => ['countryCode' => 'ms', 'name' => 'Malay', 'script' => 'Latn', 'native' => 'Bahasa Melayu'],
    'bm' => ['countryCode' => 'bm', 'name' => 'Bambara', 'script' => 'Latn', 'native' => 'bamanakan'],
    'jv' => ['countryCode' => 'jv', 'name' => 'Javanese (Latin)', 'script' => 'Latn', 'native' => 'Basa Jawa'],
    'su' => ['countryCode' => 'su', 'name' => 'Sundanese', 'script' => 'Latn', 'native' => 'Basa Sunda'],
    'bh' => ['countryCode' => 'bh', 'name' => 'Bihari', 'script' => 'Latn', 'native' => 'Bihari'],
    'bi' => ['countryCode' => 'bi', 'name' => 'Bislama', 'script' => 'Latn', 'native' => 'Bislama'],
    'nb' => ['countryCode' => 'nb', 'name' => 'Norwegian Bokmål', 'script' => 'Latn', 'native' => 'Bokmål'],
    'bs' => ['countryCode' => 'bs', 'name' => 'Bosnian', 'script' => 'Latn', 'native' => 'bosanski'],
    'br' => ['countryCode' => 'br', 'name' => 'Breton', 'script' => 'Latn', 'native' => 'brezhoneg'],
    'ca' => ['countryCode' => 'ca', 'name' => 'Catalan', 'script' => 'Latn', 'native' => 'català'],
    'ch' => ['countryCode' => 'ch', 'name' => 'Chamorro', 'script' => 'Latn', 'native' => 'Chamoru'],
    'ny' => ['countryCode' => 'ny', 'name' => 'Chewa', 'script' => 'Latn', 'native' => 'chiCheŵa'],
    'kde' => ['countryCode' => 'kde', 'name' => 'Makonde', 'script' => 'Latn', 'native' => 'Chimakonde'],
    'sn' => ['countryCode' => 'sn', 'name' => 'Shona', 'script' => 'Latn', 'native' => 'chiShona'],
    'co' => ['countryCode' => 'co', 'name' => 'Corsican', 'script' => 'Latn', 'native' => 'corsu'],
    'cy' => ['countryCode' => 'cy', 'name' => 'Welsh', 'script' => 'Latn', 'native' => 'Cymraeg'],
    'da' => ['countryCode' => 'da', 'name' => 'Danish', 'script' => 'Latn', 'native' => 'dansk'],
    'se' => ['countryCode' => 'se', 'name' => 'Northern Sami', 'script' => 'Latn', 'native' => 'davvisámegiella'],
    'de' => ['countryCode' => 'de', 'name' => 'German', 'script' => 'Latn', 'native' => 'Deutsch'],
    'luo' => ['countryCode' => 'luo', 'name' => 'Luo', 'script' => 'Latn', 'native' => 'Dholuo'],
    'nv' => ['countryCode' => 'nv', 'name' => 'Navajo', 'script' => 'Latn', 'native' => 'Diné bizaad'],
    'dua' => ['countryCode' => 'dua', 'name' => 'Duala', 'script' => 'Latn', 'native' => 'duálá'],
    'et' => ['countryCode' => 'et', 'name' => 'Estonian', 'script' => 'Latn', 'native' => 'eesti'],
    'na' => ['countryCode' => 'na', 'name' => 'Nauru', 'script' => 'Latn', 'native' => 'Ekakairũ Naoero'],
    'guz' => ['countryCode' => 'guz', 'name' => 'Ekegusii', 'script' => 'Latn', 'native' => 'Ekegusii'],
    'en' => ['countryCode' => 'en', 'name' => 'English', 'script' => 'Latn', 'native' => 'English'],
    'en-AU' => ['countryCode' => 'en-AU', 'name' => 'Australian English', 'script' => 'Latn', 'native' => 'Australian English'],
    'en-GB' => ['countryCode' => 'en-GB', 'name' => 'British English', 'script' => 'Latn', 'native' => 'British English'],
    'en-US' => ['countryCode' => 'en-US', 'name' => 'U.S. English', 'script' => 'Latn', 'native' => 'U.S. English'],
    'es' => ['countryCode' => 'es', 'name' => 'Spanish', 'script' => 'Latn', 'native' => 'español'],
    'eo' => ['countryCode' => 'eo', 'name' => 'Esperanto', 'script' => 'Latn', 'native' => 'esperanto'],
    'eu' => ['countryCode' => 'eu', 'name' => 'Basque', 'script' => 'Latn', 'native' => 'euskara'],
    'ewo' => ['countryCode' => 'ewo', 'name' => 'Ewondo', 'script' => 'Latn', 'native' => 'ewondo'],
    'ee' => ['countryCode' => 'ee', 'name' => 'Ewe', 'script' => 'Latn', 'native' => 'eʋegbe'],
    'fil' => ['countryCode' => 'fil', 'name' => 'Filipino', 'script' => 'Latn', 'native' => 'Filipino'],
    'fr' => ['countryCode' => 'fr', 'name' => 'French', 'script' => 'Latn', 'native' => 'Français'],
    'fr-CA' => ['countryCode' => 'fr-CA', 'name' => 'Canadian French', 'script' => 'Latn', 'native' => 'Français canadien'],
    'fy' => ['countryCode' => 'fy', 'name' => 'Western Frisian', 'script' => 'Latn', 'native' => 'frysk'],
    'fur' => ['countryCode' => 'fur', 'name' => 'Friulian', 'script' => 'Latn', 'native' => 'furlan'],
    'fo' => ['countryCode' => 'fo', 'name' => 'Faroese', 'script' => 'Latn', 'native' => 'føroyskt'],
    'gaa' => ['countryCode' => 'gaa', 'name' => 'Ga', 'script' => 'Latn', 'native' => 'Ga'],
    'ga' => ['countryCode' => 'ga', 'name' => 'Irish', 'script' => 'Latn', 'native' => 'Gaeilge'],
    'gv' => ['countryCode' => 'gv', 'name' => 'Manx', 'script' => 'Latn', 'native' => 'Gaelg'],
    'sm' => ['countryCode' => 'sm', 'name' => 'Samoan', 'script' => 'Latn', 'native' => 'Gagana fa’a Sāmoa'],
    'gl' => ['countryCode' => 'gl', 'name' => 'Galician', 'script' => 'Latn', 'native' => 'galego'],
    'ki' => ['countryCode' => 'ki', 'name' => 'Kikuyu', 'script' => 'Latn', 'native' => 'Gikuyu'],
    'gd' => ['countryCode' => 'gd', 'name' => 'Scottish Gaelic', 'script' => 'Latn', 'native' => 'Gàidhlig'],
    'ha' => ['countryCode' => 'ha', 'name' => 'Hausa', 'script' => 'Latn', 'native' => 'Hausa'],
    'bez' => ['countryCode' => 'bez', 'name' => 'Bena', 'script' => 'Latn', 'native' => 'Hibena'],
    'ho' => ['countryCode' => 'ho', 'name' => 'Hiri Motu', 'script' => 'Latn', 'native' => 'Hiri Motu'],
    'hr' => ['countryCode' => 'hr', 'name' => 'Croatian', 'script' => 'Latn', 'native' => 'hrvatski'],
    'bem' => ['countryCode' => 'bem', 'name' => 'Bemba', 'script' => 'Latn', 'native' => 'Ichibemba'],
    'io' => ['countryCode' => 'io', 'name' => 'Ido', 'script' => 'Latn', 'native' => 'Ido'],
    'ig' => ['countryCode' => 'ig', 'name' => 'Igbo', 'script' => 'Latn', 'native' => 'Igbo'],
    'rn' => ['countryCode' => 'rn', 'name' => 'Rundi', 'script' => 'Latn', 'native' => 'Ikirundi'],
    'ia' => ['countryCode' => 'ia', 'name' => 'Interlingua', 'script' => 'Latn', 'native' => 'interlingua'],
    'iu-Latn' => ['countryCode' => 'iu-Latn', 'name' => 'Inuktitut (Latin)', 'script' => 'Latn', 'native' => 'Inuktitut'],
    'sbp' => ['countryCode' => 'sbp', 'name' => 'Sileibi', 'script' => 'Latn', 'native' => 'Ishisangu'],
    'nd' => ['countryCode' => 'nd', 'name' => 'North Ndebele', 'script' => 'Latn', 'native' => 'isiNdebele'],
    'nr' => ['countryCode' => 'nr', 'name' => 'South Ndebele', 'script' => 'Latn', 'native' => 'isiNdebele'],
    'xh' => ['countryCode' => 'xh', 'name' => 'Xhosa', 'script' => 'Latn', 'native' => 'isiXhosa'],
    'zu' => ['countryCode' => 'zu', 'name' => 'Zulu', 'script' => 'Latn', 'native' => 'isiZulu'],
    'it' => ['countryCode' => 'it', 'name' => 'Italian', 'script' => 'Latn', 'native' => 'italiano'],
    'ik' => ['countryCode' => 'ik', 'name' => 'Inupiaq', 'script' => 'Latn', 'native' => 'Iñupiaq'],
    'dyo' => ['countryCode' => 'dyo', 'name' => 'Jola-Fonyi', 'script' => 'Latn', 'native' => 'joola'],
    'kea' => ['countryCode' => 'kea', 'name' => 'Kabuverdianu', 'script' => 'Latn', 'native' => 'kabuverdianu'],
    'kaj' => ['countryCode' => 'kaj', 'name' => 'Jju', 'script' => 'Latn', 'native' => 'Kaje'],
    'mh' => ['countryCode' => 'mh', 'name' => 'Marshallese', 'script' => 'Latn', 'native' => 'Kajin M̧ajeļ'],
    'kl' => ['countryCode' => 'kl', 'name' => 'Kalaallisut', 'script' => 'Latn', 'native' => 'kalaallisut'],
    'kln' => ['countryCode' => 'kln', 'name' => 'Kalenjin', 'script' => 'Latn', 'native' => 'Kalenjin'],
    'kr' => ['countryCode' => 'kr', 'name' => 'Kanuri', 'script' => 'Latn', 'native' => 'Kanuri'],
    'kcg' => ['countryCode' => 'kcg', 'name' => 'Tyap', 'script' => 'Latn', 'native' => 'Katab'],
    'kw' => ['countryCode' => 'kw', 'name' => 'Cornish', 'script' => 'Latn', 'native' => 'kernewek'],
    'naq' => ['countryCode' => 'naq', 'name' => 'Nama', 'script' => 'Latn', 'native' => 'Khoekhoegowab'],
    'rof' => ['countryCode' => 'rof', 'name' => 'Rombo', 'script' => 'Latn', 'native' => 'Kihorombo'],
    'kam' => ['countryCode' => 'kam', 'name' => 'Kamba', 'script' => 'Latn', 'native' => 'Kikamba'],
    'kg' => ['countryCode' => 'kg', 'name' => 'Kongo', 'script' => 'Latn', 'native' => 'Kikongo'],
    'jmc' => ['countryCode' => 'jmc', 'name' => 'Machame', 'script' => 'Latn', 'native' => 'Kimachame'],
    'rw' => ['countryCode' => 'rw', 'name' => 'Kinyarwanda', 'script' => 'Latn', 'native' => 'Kinyarwanda'],
    'asa' => ['countryCode' => 'asa', 'name' => 'Kipare', 'script' => 'Latn', 'native' => 'Kipare'],
    'rwk' => ['countryCode' => 'rwk', 'name' => 'Rwa', 'script' => 'Latn', 'native' => 'Kiruwa'],
    'saq' => ['countryCode' => 'saq', 'name' => 'Samburu', 'script' => 'Latn', 'native' => 'Kisampur'],
    'ksb' => ['countryCode' => 'ksb', 'name' => 'Shambala', 'script' => 'Latn', 'native' => 'Kishambaa'],
    'swc' => ['countryCode' => 'swc', 'name' => 'Congo Swahili', 'script' => 'Latn', 'native' => 'Kiswahili ya Kongo'],
    'sw' => ['countryCode' => 'sw', 'name' => 'Swahili', 'script' => 'Latn', 'native' => 'Kiswahili'],
    'dav' => ['countryCode' => 'dav', 'name' => 'Dawida', 'script' => 'Latn', 'native' => 'Kitaita'],
    'teo' => ['countryCode' => 'teo', 'name' => 'Teso', 'script' => 'Latn', 'native' => 'Kiteso'],
    'khq' => ['countryCode' => 'khq', 'name' => 'Koyra Chiini', 'script' => 'Latn', 'native' => 'Koyra ciini'],
    'ses' => ['countryCode' => 'ses', 'name' => 'Songhay', 'script' => 'Latn', 'native' => 'Koyraboro senni'],
    'mfe' => ['countryCode' => 'mfe', 'name' => 'Morisyen', 'script' => 'Latn', 'native' => 'kreol morisien'],
    'ht' => ['countryCode' => 'ht', 'name' => 'Haitian', 'script' => 'Latn', 'native' => 'Kreyòl ayisyen'],
    'kj' => ['countryCode' => 'kj', 'name' => 'Kuanyama', 'script' => 'Latn', 'native' => 'Kwanyama'],
    'ksh' => ['countryCode' => 'ksh', 'name' => 'Kölsch', 'script' => 'Latn', 'native' => 'Kölsch'],
    'ebu' => ['countryCode' => 'ebu', 'name' => 'Kiembu', 'script' => 'Latn', 'native' => 'Kĩembu'],
    'mer' => ['countryCode' => 'mer', 'name' => 'Kimîîru', 'script' => 'Latn', 'native' => 'Kĩmĩrũ'],
    'lag' => ['countryCode' => 'lag', 'name' => 'Langi', 'script' => 'Latn', 'native' => 'Kɨlaangi'],
    'lah' => ['countryCode' => 'lah', 'name' => 'Lahnda', 'script' => 'Latn', 'native' => 'Lahnda'],
    'la' => ['countryCode' => 'la', 'name' => 'Latin', 'script' => 'Latn', 'native' => 'latine'],
    'lv' => ['countryCode' => 'lv', 'name' => 'Latvian', 'script' => 'Latn', 'native' => 'latviešu'],
    'to' => ['countryCode' => 'to', 'name' => 'Tongan', 'script' => 'Latn', 'native' => 'lea fakatonga'],
    'lt' => ['countryCode' => 'lt', 'name' => 'Lithuanian', 'script' => 'Latn', 'native' => 'lietuvių'],
    'li' => ['countryCode' => 'li', 'name' => 'Limburgish', 'script' => 'Latn', 'native' => 'Limburgs'],
    'ln' => ['countryCode' => 'ln', 'name' => 'Lingala', 'script' => 'Latn', 'native' => 'lingála'],
    'lg' => ['countryCode' => 'lg', 'name' => 'Ganda', 'script' => 'Latn', 'native' => 'Luganda'],
    'luy' => ['countryCode' => 'luy', 'name' => 'Oluluyia', 'script' => 'Latn', 'native' => 'Luluhia'],
    'lb' => ['countryCode' => 'lb', 'name' => 'Luxembourgish', 'script' => 'Latn', 'native' => 'Lëtzebuergesch'],
    'hu' => ['countryCode' => 'hu', 'name' => 'Hungarian', 'script' => 'Latn', 'native' => 'magyar'],
    'mgh' => ['countryCode' => 'mgh', 'name' => 'Makhuwa-Meetto', 'script' => 'Latn', 'native' => 'Makua'],
    'mg' => ['countryCode' => 'mg', 'name' => 'Malagasy', 'script' => 'Latn', 'native' => 'Malagasy'],
    'mt' => ['countryCode' => 'mt', 'name' => 'Maltese', 'script' => 'Latn', 'native' => 'Malti'],
    'mtr' => ['countryCode' => 'mtr', 'name' => 'Mewari', 'script' => 'Latn', 'native' => 'Mewari'],
    'mua' => ['countryCode' => 'mua', 'name' => 'Mundang', 'script' => 'Latn', 'native' => 'Mundang'],
    'mi' => ['countryCode' => 'mi', 'name' => 'Māori', 'script' => 'Latn', 'native' => 'Māori'],
    'nl' => ['countryCode' => 'nl', 'name' => 'Dutch', 'script' => 'Latn', 'native' => 'Nederlands'],
    'nmg' => ['countryCode' => 'nmg', 'name' => 'Kwasio', 'script' => 'Latn', 'native' => 'ngumba'],
    'yav' => ['countryCode' => 'yav', 'name' => 'Yangben', 'script' => 'Latn', 'native' => 'nuasue'],
    'nn' => ['countryCode' => 'nn', 'name' => 'Norwegian Nynorsk', 'script' => 'Latn', 'native' => 'nynorsk'],
    'oc' => ['countryCode' => 'oc', 'name' => 'Occitan', 'script' => 'Latn', 'native' => 'occitan'],
    'ang' => ['countryCode' => 'ang', 'name' => 'Old English', 'script' => 'Runr', 'native' => 'Old English'],
    'xog' => ['countryCode' => 'xog', 'name' => 'Soga', 'script' => 'Latn', 'native' => 'Olusoga'],
    'om' => ['countryCode' => 'om', 'name' => 'Oromo', 'script' => 'Latn', 'native' => 'Oromoo'],
    'ng' => ['countryCode' => 'ng', 'name' => 'Ndonga', 'script' => 'Latn', 'native' => 'OshiNdonga'],
    'hz' => ['countryCode' => 'hz', 'name' => 'Herero', 'script' => 'Latn', 'native' => 'Otjiherero'],
    'uz-Latn' => ['countryCode' => 'uz-Latn', 'name' => 'Uzbek (Latin)', 'script' => 'Latn', 'native' => 'oʼzbekcha'],
    'nds' => ['countryCode' => 'nds', 'name' => 'Low German', 'script' => 'Latn', 'native' => 'Plattdüütsch'],
    'pl' => ['countryCode' => 'pl', 'name' => 'Polish', 'script' => 'Latn', 'native' => 'polski'],
    'pt' => ['countryCode' => 'pt', 'name' => 'Portuguese', 'script' => 'Latn', 'native' => 'português'],
    'pt-BR' => ['countryCode' => 'pt-BR', 'name' => 'Brazilian Portuguese', 'script' => 'Latn', 'native' => 'português do Brasil'],
    'ff' => ['countryCode' => 'ff', 'name' => 'Fulah', 'script' => 'Latn', 'native' => 'Pulaar'],
    'pi' => ['countryCode' => 'pi', 'name' => 'Pahari-Potwari', 'script' => 'Latn', 'native' => 'Pāli'],
    'aa' => ['countryCode' => 'aa', 'name' => 'Afar', 'script' => 'Latn', 'native' => 'Qafar'],
    'ty' => ['countryCode' => 'ty', 'name' => 'Tahitian', 'script' => 'Latn', 'native' => 'Reo Māohi'],
    'ksf' => ['countryCode' => 'ksf', 'name' => 'Bafia', 'script' => 'Latn', 'native' => 'rikpa'],
    'ro' => ['countryCode' => 'ro', 'name' => 'Romanian', 'script' => 'Latn', 'native' => 'română'],
    'cgg' => ['countryCode' => 'cgg', 'name' => 'Chiga', 'script' => 'Latn', 'native' => 'Rukiga'],
    'rm' => ['countryCode' => 'rm', 'name' => 'Romansh', 'script' => 'Latn', 'native' => 'rumantsch'],
    'qu' => ['countryCode' => 'qu', 'name' => 'Quechua', 'script' => 'Latn', 'native' => 'Runa Simi'],
    'nyn' => ['countryCode' => 'nyn', 'name' => 'Nyankole', 'script' => 'Latn', 'native' => 'Runyankore'],
    'ssy' => ['countryCode' => 'ssy', 'name' => 'Saho', 'script' => 'Latn', 'native' => 'Saho'],
    'sc' => ['countryCode' => 'sc', 'name' => 'Sardinian', 'script' => 'Latn', 'native' => 'sardu'],
    'de-CH' => ['countryCode' => 'de-CH', 'name' => 'Swiss High German', 'script' => 'Latn', 'native' => 'Schweizer Hochdeutsch'],
    'gsw' => ['countryCode' => 'gsw', 'name' => 'Swiss German', 'script' => 'Latn', 'native' => 'Schwiizertüütsch'],
    'trv' => ['countryCode' => 'trv', 'name' => 'Taroko', 'script' => 'Latn', 'native' => 'Seediq'],
    'seh' => ['countryCode' => 'seh', 'name' => 'Sena', 'script' => 'Latn', 'native' => 'sena'],
    'nso' => ['countryCode' => 'nso', 'name' => 'Northern Sotho', 'script' => 'Latn', 'native' => 'Sesotho sa Leboa'],
    'st' => ['countryCode' => 'st', 'name' => 'Southern Sotho', 'script' => 'Latn', 'native' => 'Sesotho'],
    'tn' => ['countryCode' => 'tn', 'name' => 'Tswana', 'script' => 'Latn', 'native' => 'Setswana'],
    'sq' => ['countryCode' => 'sq', 'name' => 'Albanian', 'script' => 'Latn', 'native' => 'shqip'],
    'sid' => ['countryCode' => 'sid', 'name' => 'Sidamo', 'script' => 'Latn', 'native' => 'Sidaamu Afo'],
    'ss' => ['countryCode' => 'ss', 'name' => 'Swati', 'script' => 'Latn', 'native' => 'Siswati'],
    'sk' => ['countryCode' => 'sk', 'name' => 'Slovak', 'script' => 'Latn', 'native' => 'slovenčina'],
    'sl' => ['countryCode' => 'sl', 'name' => 'Slovene', 'script' => 'Latn', 'native' => 'slovenščina'],
    'so' => ['countryCode' => 'so', 'name' => 'Somali', 'script' => 'Latn', 'native' => 'Soomaali'],
    'sr-Latn' => ['countryCode' => 'sr-Latn', 'name' => 'Serbian (Latin)', 'script' => 'Latn', 'native' => 'Srpski'],
    'sh' => ['countryCode' => 'sh', 'name' => 'Serbo-Croatian', 'script' => 'Latn', 'native' => 'srpskohrvatski'],
    'fi' => ['countryCode' => 'fi', 'name' => 'Finnish', 'script' => 'Latn', 'native' => 'suomi'],
    'sv' => ['countryCode' => 'sv', 'name' => 'Swedish', 'script' => 'Latn', 'native' => 'svenska'],
    'sg' => ['countryCode' => 'sg', 'name' => 'Sango', 'script' => 'Latn', 'native' => 'Sängö'],
    'tl' => ['countryCode' => 'tl', 'name' => 'Tagalog', 'script' => 'Latn', 'native' => 'Tagalog'],
    'tzm-Latn' => ['countryCode' => 'tzm-Latn', 'name' => 'Central Atlas Tamazight (Latin)', 'script' => 'Latn', 'native' => 'Tamazight'],
    'kab' => ['countryCode' => 'kab', 'name' => 'Kabyle', 'script' => 'Latn', 'native' => 'Taqbaylit'],
    'twq' => ['countryCode' => 'twq', 'name' => 'Tasawaq', 'script' => 'Latn', 'native' => 'Tasawaq senni'],
    'shi' => ['countryCode' => 'shi', 'name' => 'Tachelhit (Latin)', 'script' => 'Latn', 'native' => 'Tashelhit'],
    'nus' => ['countryCode' => 'nus', 'name' => 'Nuer', 'script' => 'Latn', 'native' => 'Thok Nath'],
    'vi' => ['countryCode' => 'vi', 'name' => 'Vietnamese', 'script' => 'Latn', 'native' => 'Tiếng Việt'],
    'tg-Latn' => ['countryCode' => 'tg-Latn', 'name' => 'Tajik (Latin)', 'script' => 'Latn', 'native' => 'tojikī'],
    'lu' => ['countryCode' => 'lu', 'name' => 'Luba-Katanga', 'script' => 'Latn', 'native' => 'Tshiluba'],
    've' => ['countryCode' => 've', 'name' => 'Venda', 'script' => 'Latn', 'native' => 'Tshivenḓa'],
    'tw' => ['countryCode' => 'tw', 'name' => 'Twi', 'script' => 'Latn', 'native' => 'Twi'],
    'tr' => ['countryCode' => 'tr', 'name' => 'Turkish', 'script' => 'Latn', 'native' => 'Türkçe'],
    'ale' => ['countryCode' => 'ale', 'name' => 'Aleut', 'script' => 'Latn', 'native' => 'Unangax tunuu'],
    'ca-valencia' => ['countryCode' => 'ca-valencia', 'name' => 'Valencian', 'script' => 'Latn', 'native' => 'valencià'],
    'vai-Latn' => ['countryCode' => 'vai-Latn', 'name' => 'Vai (Latin)', 'script' => 'Latn', 'native' => 'Viyamíĩ'],
    'vo' => ['countryCode' => 'vo', 'name' => 'Volapük', 'script' => 'Latn', 'native' => 'Volapük'],
    'fj' => ['countryCode' => 'fj', 'name' => 'Fijian', 'script' => 'Latn', 'native' => 'vosa Vakaviti'],
    'wa' => ['countryCode' => 'wa', 'name' => 'Walloon', 'script' => 'Latn', 'native' => 'Walon'],
    'wae' => ['countryCode' => 'wae', 'name' => 'Walser', 'script' => 'Latn', 'native' => 'Walser'],
    'wen' => ['countryCode' => 'wen', 'name' => 'Sorbian', 'script' => 'Latn', 'native' => 'Wendic'],
    'wo' => ['countryCode' => 'wo', 'name' => 'Wolof', 'script' => 'Latn', 'native' => 'Wolof'],
    'ts' => ['countryCode' => 'ts', 'name' => 'Tsonga', 'script' => 'Latn', 'native' => 'Xitsonga'],
    'dje' => ['countryCode' => 'dje', 'name' => 'Zarma', 'script' => 'Latn', 'native' => 'Zarmaciine'],
    'yo' => ['countryCode' => 'yo', 'name' => 'Yoruba', 'script' => 'Latn', 'native' => 'Èdè Yorùbá'],
    'de-AT' => ['countryCode' => 'de-AT', 'name' => 'Austrian German', 'script' => 'Latn', 'native' => 'Österreichisches Deutsch'],
    'is' => ['countryCode' => 'is', 'name' => 'Icelandic', 'script' => 'Latn', 'native' => 'íslenska'],
    'cs' => ['countryCode' => 'cs', 'name' => 'Czech', 'script' => 'Latn', 'native' => 'čeština'],
    'bas' => ['countryCode' => 'bas', 'name' => 'Basa', 'script' => 'Latn', 'native' => 'Ɓàsàa'],
    'mas' => ['countryCode' => 'mas', 'name' => 'Masai', 'script' => 'Latn', 'native' => 'ɔl-Maa'],
    'haw' => ['countryCode' => 'haw', 'name' => 'Hawaiian', 'script' => 'Latn', 'native' => 'ʻŌlelo Hawaiʻi'],
    'el' => ['countryCode' => 'el', 'name' => 'Greek', 'script' => 'Grek', 'native' => 'Ελληνικά'],
    'uz' => ['countryCode' => 'uz', 'name' => 'Uzbek (Cyrillic)', 'script' => 'Cyrl', 'native' => 'Ўзбек'],
    'az-Cyrl' => ['countryCode' => 'az-Cyrl', 'name' => 'Azerbaijani (Cyrillic)', 'script' => 'Cyrl', 'native' => 'Азәрбајҹан'],
    'ab' => ['countryCode' => 'ab', 'name' => 'Abkhazian', 'script' => 'Cyrl', 'native' => 'Аҧсуа'],
    'os' => ['countryCode' => 'os', 'name' => 'Ossetic', 'script' => 'Cyrl', 'native' => 'Ирон'],
    'ky' => ['countryCode' => 'ky', 'name' => 'Kyrgyz', 'script' => 'Cyrl', 'native' => 'Кыргыз'],
    'sr' => ['countryCode' => 'sr', 'name' => 'Serbian (Cyrillic)', 'script' => 'Cyrl', 'native' => 'Српски'],
    'av' => ['countryCode' => 'av', 'name' => 'Avaric', 'script' => 'Cyrl', 'native' => 'авар мацӀ'],
    'ady' => ['countryCode' => 'ady', 'name' => 'Adyghe', 'script' => 'Cyrl', 'native' => 'адыгэбзэ'],
    'ba' => ['countryCode' => 'ba', 'name' => 'Bashkir', 'script' => 'Cyrl', 'native' => 'башҡорт теле'],
    'be' => ['countryCode' => 'be', 'name' => 'Belarusian', 'script' => 'Cyrl', 'native' => 'беларуская'],
    'bg' => ['countryCode' => 'bg', 'name' => 'Bulgarian', 'script' => 'Cyrl', 'native' => 'български'],
    'kv' => ['countryCode' => 'kv', 'name' => 'Komi', 'script' => 'Cyrl', 'native' => 'коми кыв'],
    'mk' => ['countryCode' => 'mk', 'name' => 'Macedonian', 'script' => 'Cyrl', 'native' => 'македонски'],
    'mn' => ['countryCode' => 'mn', 'name' => 'Mongolian (Cyrillic)', 'script' => 'Cyrl', 'native' => 'монгол'],
    'ce' => ['countryCode' => 'ce', 'name' => 'Chechen', 'script' => 'Cyrl', 'native' => 'нохчийн мотт'],
    'ru' => ['countryCode' => 'ru', 'name' => 'Russian', 'script' => 'Cyrl', 'native' => 'русский'],
    'sah' => ['countryCode' => 'sah', 'name' => 'Yakut', 'script' => 'Cyrl', 'native' => 'саха тыла'],
    'tt' => ['countryCode' => 'tt', 'name' => 'Tatar', 'script' => 'Cyrl', 'native' => 'татар теле'],
    'tg' => ['countryCode' => 'tg', 'name' => 'Tajik (Cyrillic)', 'script' => 'Cyrl', 'native' => 'тоҷикӣ'],
    'tk' => ['countryCode' => 'tk', 'name' => 'Turkmen', 'script' => 'Cyrl', 'native' => 'түркменче'],
    'uk' => ['countryCode' => 'uk', 'name' => 'Ukrainian', 'script' => 'Cyrl', 'native' => 'українська'],
    'cv' => ['countryCode' => 'cv', 'name' => 'Chuvash', 'script' => 'Cyrl', 'native' => 'чӑваш чӗлхи'],
    'cu' => ['countryCode' => 'cu', 'name' => 'Church Slavic', 'script' => 'Cyrl', 'native' => 'ѩзыкъ словѣньскъ'],
    'kk' => ['countryCode' => 'kk', 'name' => 'Kazakh', 'script' => 'Cyrl', 'native' => 'қазақ тілі'],
    'hy' => ['countryCode' => 'hy', 'name' => 'Armenian', 'script' => 'Armn', 'native' => 'Հայերէն'],
    'yi' => ['countryCode' => 'yi', 'name' => 'Yiddish', 'script' => 'Hebr', 'native' => 'ייִדיש'],
    'he' => ['countryCode' => 'he', 'name' => 'Hebrew', 'script' => 'Hebr', 'native' => 'עברית'],
    'ug' => ['countryCode' => 'ug', 'name' => 'Uyghur', 'script' => 'Arab', 'native' => 'ئۇيغۇرچە'],
    'ur' => ['countryCode' => 'ur', 'name' => 'Urdu', 'script' => 'Arab', 'native' => 'اردو'],
    'ar' => ['countryCode' => 'ar', 'name' => 'Arabic', 'script' => 'Arab', 'native' => 'العربية'],
    'uz-Arab' => ['countryCode' => 'uz-Arab', 'name' => 'Uzbek (Arabic)', 'script' => 'Arab', 'native' => 'اۉزبېک'],
    'tg-Arab' => ['countryCode' => 'tg-Arab', 'name' => 'Tajik (Arabic)', 'script' => 'Arab', 'native' => 'تاجیکی'],
    'sd' => ['countryCode' => 'sd', 'name' => 'Sindhi', 'script' => 'Arab', 'native' => 'سنڌي'],
    'fa' => ['countryCode' => 'fa', 'name' => 'Persian', 'script' => 'Arab', 'native' => 'فارسی'],
    'pa-Arab' => ['countryCode' => 'pa-Arab', 'name' => 'Punjabi (Arabic)', 'script' => 'Arab', 'native' => 'پنجاب'],
    'ps' => ['countryCode' => 'ps', 'name' => 'Pashto', 'script' => 'Arab', 'native' => 'پښتو'],
    'ks' => ['countryCode' => 'ks', 'name' => 'Kashmiri (Arabic)', 'script' => 'Arab', 'native' => 'کأشُر'],
    'ku' => ['countryCode' => 'ku', 'name' => 'Kurdish', 'script' => 'Arab', 'native' => 'کوردی'],
    'dv' => ['countryCode' => 'dv', 'name' => 'Divehi', 'script' => 'Thaa', 'native' => 'ދިވެހިބަސް'],
    'ks-Deva' => ['countryCode' => 'ks-Deva', 'name' => 'Kashmiri (Devaganari)', 'script' => 'Deva', 'native' => 'कॉशुर'],
    'kok' => ['countryCode' => 'kok', 'name' => 'Konkani', 'script' => 'Deva', 'native' => 'कोंकणी'],
    'doi' => ['countryCode' => 'doi', 'name' => 'Dogri', 'script' => 'Deva', 'native' => 'डोगरी'],
    'ne' => ['countryCode' => 'ne', 'name' => 'Nepali', 'script' => 'Deva', 'native' => 'नेपाली'],
    'pra' => ['countryCode' => 'pra', 'name' => 'Prakrit', 'script' => 'Deva', 'native' => 'प्राकृत'],
    'brx' => ['countryCode' => 'brx', 'name' => 'Bodo', 'script' => 'Deva', 'native' => 'बड़ो'],
    'bra' => ['countryCode' => 'bra', 'name' => 'Braj', 'script' => 'Deva', 'native' => 'ब्रज भाषा'],
    'mr' => ['countryCode' => 'mr', 'name' => 'Marathi', 'script' => 'Deva', 'native' => 'मराठी'],
    'mai' => ['countryCode' => 'mai', 'name' => 'Maithili', 'script' => 'Tirh', 'native' => 'मैथिली'],
    'raj' => ['countryCode' => 'raj', 'name' => 'Rajasthani', 'script' => 'Deva', 'native' => 'राजस्थानी'],
    'sa' => ['countryCode' => 'sa', 'name' => 'Sanskrit', 'script' => 'Deva', 'native' => 'संस्कृतम्'],
    'hi' => ['countryCode' => 'hi', 'name' => 'Hindi', 'script' => 'Deva', 'native' => 'हिन्दी'],
    'as' => ['countryCode' => 'as', 'name' => 'Assamese', 'script' => 'Beng', 'native' => 'অসমীয়া'],
    'bn' => ['countryCode' => 'bn', 'name' => 'Bengali', 'script' => 'Beng', 'native' => 'বাংলা'],
    'mni' => ['countryCode' => 'mni', 'name' => 'Manipuri', 'script' => 'Beng', 'native' => 'মৈতৈ'],
    'pa' => ['countryCode' => 'pa', 'name' => 'Punjabi (Gurmukhi)', 'script' => 'Guru', 'native' => 'ਪੰਜਾਬੀ'],
    'gu' => ['countryCode' => 'gu', 'name' => 'Gujarati', 'script' => 'Gujr', 'native' => 'ગુજરાતી'],
    'or' => ['countryCode' => 'or', 'name' => 'Oriya', 'script' => 'Orya', 'native' => 'ଓଡ଼ିଆ'],
    'ta' => ['countryCode' => 'ta', 'name' => 'Tamil', 'script' => 'Taml', 'native' => 'தமிழ்'],
    'te' => ['countryCode' => 'te', 'name' => 'Telugu', 'script' => 'Telu', 'native' => 'తెలుగు'],
    'kn' => ['countryCode' => 'kn', 'name' => 'Kannada', 'script' => 'Knda', 'native' => 'ಕನ್ನಡ'],
    'ml' => ['countryCode' => 'ml', 'name' => 'Malayalam', 'script' => 'Mlym', 'native' => 'മലയാളം'],
    'si' => ['countryCode' => 'si', 'name' => 'Sinhala', 'script' => 'Sinh', 'native' => 'සිංහල'],
    'th' => ['countryCode' => 'th', 'name' => 'Thai', 'script' => 'Thai', 'native' => 'ไทย'],
    'lo' => ['countryCode' => 'lo', 'name' => 'Lao', 'script' => 'Laoo', 'native' => 'ລາວ'],
    'bo' => ['countryCode' => 'bo', 'name' => 'Tibetan', 'script' => 'Tibt', 'native' => 'པོད་སྐད་'],
    'dz' => ['countryCode' => 'dz', 'name' => 'Dzongkha', 'script' => 'Tibt', 'native' => 'རྫོང་ཁ'],
    'my' => ['countryCode' => 'my', 'name' => 'Burmese', 'script' => 'Mymr', 'native' => 'မြန်မာဘာသာ'],
    'ka' => ['countryCode' => 'ka', 'name' => 'Georgian', 'script' => 'Geor', 'native' => 'ქართული'],
    'byn' => ['countryCode' => 'byn', 'name' => 'Blin', 'script' => 'Ethi', 'native' => 'ብሊን'],
    'tig' => ['countryCode' => 'tig', 'name' => 'Tigre', 'script' => 'Ethi', 'native' => 'ትግረ'],
    'ti' => ['countryCode' => 'ti', 'name' => 'Tigrinya', 'script' => 'Ethi', 'native' => 'ትግርኛ'],
    'am' => ['countryCode' => 'am', 'name' => 'Amharic', 'script' => 'Ethi', 'native' => 'አማርኛ'],
    'wal' => ['countryCode' => 'wal', 'name' => 'Wolaytta', 'script' => 'Ethi', 'native' => 'ወላይታቱ'],
    'chr' => ['countryCode' => 'chr', 'name' => 'Cherokee', 'script' => 'Cher', 'native' => 'ᏣᎳᎩ'],
    'iu' => ['countryCode' => 'iu', 'name' => 'Inuktitut (Canadian Aboriginal Syllabics)', 'script' => 'Cans', 'native' => 'ᐃᓄᒃᑎᑐᑦ'],
    'oj' => ['countryCode' => 'oj', 'name' => 'Ojibwa', 'script' => 'Cans', 'native' => 'ᐊᓂᔑᓈᐯᒧᐎᓐ'],
    'cr' => ['countryCode' => 'cr', 'name' => 'Cree', 'script' => 'Cans', 'native' => 'ᓀᐦᐃᔭᐍᐏᐣ'],
    'km' => ['countryCode' => 'km', 'name' => 'Khmer', 'script' => 'Khmr', 'native' => 'ភាសាខ្មែរ'],
    'mn-Mong' => ['countryCode' => 'mn-Mong', 'name' => 'Mongolian (Mongolian)', 'script' => 'Mong', 'native' => 'ᠮᠣᠨᠭᠭᠣᠯ ᠬᠡᠯᠡ'],
    'shi-Tfng' => ['countryCode' => 'shi-Tfng', 'name' => 'Tachelhit (Tifinagh)', 'script' => 'Tfng', 'native' => 'ⵜⴰⵎⴰⵣⵉⵖⵜ'],
    'tzm' => ['countryCode' => 'tzm', 'name' => 'Central Atlas Tamazight (Tifinagh)', 'script' => 'Tfng', 'native' => 'ⵜⴰⵎⴰⵣⵉⵖⵜ'],
    'yue' => ['countryCode' => 'yue', 'name' => 'Yue', 'script' => 'Hant', 'native' => '廣州話'],
    'ja' => ['countryCode' => 'ja', 'name' => 'Japanese', 'script' => 'Jpan', 'native' => '日本語'],
    'zh' => ['countryCode' => 'zh', 'name' => 'Chinese (Simplified)', 'script' => 'Hans', 'native' => '简体中文'],
    'zh-Hant' => ['countryCode' => 'zh-Hant', 'name' => 'Chinese (Traditional)', 'script' => 'Hant', 'native' => '繁體中文'],
    'ii' => ['countryCode' => 'ii', 'name' => 'Sichuan Yi', 'script' => 'Yiii', 'native' => 'ꆈꌠꉙ'],
    'vai' => ['countryCode' => 'vai', 'name' => 'Vai (Vai)', 'script' => 'Vaii', 'native' => 'ꕙꔤ'],
    'jv-Java' => ['countryCode' => 'jv-Java', 'name' => 'Javanese (Javanese)', 'script' => 'Java', 'native' => 'ꦧꦱꦗꦮ'],
    'ko' => ['countryCode' => 'ko', 'name' => 'Korean', 'script' => 'Hang', 'native' => '한국어'],
];